# Generated by Django 3.1.1 on 2020-09-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
